menu/menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('menu_app.urls', namespace='menu_app')),
    path('admin/', admin.site.urls),
]

menu/menu_app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'menu_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('v2/', views.index_second, name='index_second'),
    path('v2/<int:pk>/', views.index_second, name='index_second_item'),
    path('<int:pk>/', views.index, name='menu_app_name')
]

menu/menu_app/models.py
from django.db import models


class Item(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название пункта меню',
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name='слаг',
        unique=True,
    )
       
    def __str__(self):
        return self.title


class Menu(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Название меню',
    )
    items = models.ManyToManyField(
        Item,
        through=('ItemMenu'),
        related_name='items_list'
    )
    submenu = models.ManyToManyField(
        'Menu',
        through=('MenuSub'),
        related_name='sub_menu'
    )
    
    def __str__(self):
        return self.title


class ItemMenu(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name='item'
    )
    menu = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='menu'
    )
    
    def __str__(self):
        return f'{self.menu.title} {self.item.title}'
    
    
class MenuSub(models.Model):
    menu_1 = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='menu_1'
    )
    menu_2 = models.ForeignKey(
        Menu,
        on_delete=models.CASCADE,
        related_name='menu_2'
    )
    def __str__(self):
        return f'{self.menu_1.title} {self.menu_2.title}'

menu/menu_app/views.py
from django.shortcuts import render

from .models import Menu

def index(request, pk=None):
    template = 'menu/index.html'
    menu = Menu.objects.all()
    if pk == None:
        context = {
            'menu' : menu,
        }
        return render(request, template, context)
    else:
        menu = Menu.objects.prefetch_related('items', 'submenu').get(pk=pk)
        context = {
            'menu' : menu,
            'pk': pk,
        }
        return render(request, template, context)


def index_second(request, pk=None):
    menu = Menu.objects.prefetch_related('items', 'submenu').all()
    template = 'menu/index_second.html'
    if pk == None:
        context = {
            'menu': menu,
        }
        return render(request, template, context)
    else:
        context = {
            'menu': menu,
            'pk': pk,
        }        
        return render(request, template, context)

menu/menu_app/templates/menu/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
</head>
<body>
  <div class="container">
    <a href='../' class='main'><h1>Главная страница</h1></a>
    {% include './menu_template.html' %}  
  </div>
</body>
</html>

menu/menu_app/templates/menu/index_second.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Document</title>
</head>
<body>
  <div class="container">
    <a href='../' class='main'><h1>Главная страница</h1></a>
    {% include './menu_template_2.html' %}  
  </div>
  <a href={% url 'menu_app:index' %} class='main'><h1>Первый вариант</h1></a>
</body>
</html>

menu/menu_app/templates/menu/menu_template.html
{% load static %}


{% if pk == None %}
  {% for i in menu %}
    <div class="menu_link">
      <a class='link_class' href="{% url 'menu_app:menu_app_name' i.pk %}">{{ i }}</a>
    </div>
    <hr>
  {% endfor %}

{% else %}
  <h2 class='main'> {{ menu }} </h2>
  {% for i in menu.items.all %}
    <div class="item_link">
        <a class='link_class' href="#">{{ i }}</a>
    </div>
  {% endfor %}
  {% for i in menu.submenu.all %}
    <div class="menu_link">
      <a class='link_class' href="{% url 'menu_app:menu_app_name' i.pk %}">{{ i }}</a>
    </div>
    {% for j in i.items.all %}
      <div class="first_lvl_menu item_link">
        <a class='link_class' href="#">{{ j }}</a>
      </div>
    {% endfor %}
    {% for g in i.submenu.all  %}
      <div class="menu_link first_lvl_menu">
        <a class='link_class' href="{% url 'menu_app:menu_app_name' g.pk %}">{{ g }}</a>
      </div>
    {% endfor %}
  {% endfor %}
{% endif %}

<br>
<br>
<br>
<br>

<h1 class='main'> <a href="{% url 'menu_app:index_second' %}">Второй вариант </h1>

menu/menu_app/templates/menu/menu_template_2.html
{% load static %}

{% if pk == None %}
  {% for i in menu %}
    <div class="menu_container">
      <div class="menu_link">
          <a class='link_class' href="{% url 'menu_app:index_second_item' i.pk %}">{{ i }}</a>
      </div>
    </div>
  {% endfor %}
{% else %}
  {% for i in menu %}
    <div class="menu_container">
      {% if i.pk == pk %}
        <div class="menu_link">
          <a class='link_class'>{{ i }}</a>
        </div>
      {% else %}
        <div class="menu_link">
          <a class='link_class' href="{% url 'menu_app:index_second_item' i.pk %}">{{ i }}</a>
        </div>
      {% endif %}
      {% if i.pk == pk %}
        {% for j in i.items.all %}
          <div class="first_lvl_menu item_link">
            <a class='link_class' href="#">{{ j }}</a>
          </div>
        {% endfor %}
        {% for k in i.submenu.all %}
          <div class="menu_link first_lvl_menu">
            <a class='link_class' href="{% url 'menu_app:index_second_item' k.pk %}">{{ k }}</a>
          </div>
          {% for g in k.items.all %}
            <div class="second_lvl_menu item_link">
              <a class='link_class' href="#">{{ g }}</a>
            </div>
          {% endfor %}
          {% for h in k.submenu.all  %}
          <div class="menu_link second_lvl_menu">
            <a class='link_class' href="{% url 'menu_app:index_second_item' h.pk %}">{{ h }}</a>
          </div>
          {% endfor %}
        {% endfor %}
      {% endif %}
    </div>
  {% endfor %}
{% endif %}